### ISSUE TITLE
Nota informativa sobre la web

### ISSUE THREAD

**Issue by Daniel-Velasco-Lopez** [SistemasTecTlaxiaco/actividad-9-nota-informativa-equipo-daniel#1]
Daniel Velasco López
Edgar Mauricio Sarmiento Ruiz
Sandy Marissa García Santiago

[Nota Informativa.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-nota-informativa-equipo-daniel/files/9953607/Nota.Informativa.pdf)

**Comment by YaelTrinidad** [comment]
ACTIVIDAD 9 "NOTA INFORMATIVA DE LA WEB"
DE ACUERDO A LA RUBRICA OBTUVIERON EL ("20%") DEL 20% QUE EQUIVALE LA ACTIVIDAD.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
